Chapter5
Ruslan357/Alex-Ruslan pull request #4
Opened 2022-06-09 06:14 UTC by Ruslan357

2022-06-09 06:28 UTC, auraz requested changes
Minor comments, continue

2022-06-09 06:28 UTC, auraz commented on .gitignore
> +.idea
add newline

2022-06-09 06:28 UTC, auraz commented on 5.14.py
> +        print("No, that doesn’t work.\n")
Looks good

2022-06-09 06:28 UTC, auraz commented on 5.14.py
> +        print("Yes\n")
Looks good

2022-06-14 05:54 UTC, Ruslan357 commented on .gitignore
> +.idea
Done!

2022-06-14 05:54 UTC, Ruslan357 commented on 5.14.py
> +        print("No, that doesn’t work.\n")
Thank you

2022-06-14 05:54 UTC, Ruslan357 commented on 5.14.py
> +        print("Yes\n")
Thank you

2022-06-23 05:45 UTC, merged